import type { Metadata } from "next";
import Header from "../components/header";

export const metadata: Metadata = {
  title: "Recipe and item page",
  description: "Generated by create next app",
};

export default function FridgeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>
      <Header />
      {children}
    </section>
  );
}
